from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from urllib.parse import quote
import os
import pandas as pd

os.system("")
os.environ["WDM_LOG_LEVEL"] = "0"

print("Process started...")

df = pd.read_excel("./student_info.xlsx")
numbers = df["Phone Number"].tolist() # Get the list of numbers from the excel sheet

total_number=len(numbers)
print('We found ' + str(total_number) + ' numbers in the file')
delay = 60

options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=options)
print('Once your browser opens up sign in to web whatsapp')
driver.get('https://web.whatsapp.com')
input("AFTER logging into Whatsapp Web is complete and your chats are visible, press ENTER...")

for idx, number in enumerate(numbers):
	number = str(number)
	student_name = df["Name"][idx] # Get the name of the student from the excel sheet

	# Personalize the message according to the your needs
	message = f"Hello {student_name},\nThis message is generated by an automated messaging system.\nThank You."
	message = quote(message) # URL Encode the message

	if number == "": # If the number is empty, this will skip all the code below and continue to the next number
		continue
	print('{}/{} => Sending message to {}.'.format((idx+1), total_number, number))
	try:
		url = 'https://web.whatsapp.com/send?phone=+91' + number + '&text=' + message
		sent = False
		for i in range(3):
			if not sent:
				driver.get(url)
				try:
					click_btn = WebDriverWait(driver, delay).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[2]/button')))
				except Exception as e:
					print(f"\nFailed to send message to: {number}, retry ({i+1}/3)")
					print("Make sure your phone and computer is connected to the internet.")
					print("If there is an alert, please dismiss it.")
				else:
					sleep(1)
					click_btn.click()
					sent=True
					sleep(3)
					print('Message sent to: ' + number + ' successfully!\n')
	except Exception as e:
		print('Failed to send message to ' + number + str(e))
driver.close()
